package javaTest;

import java.io.IOException;

/**
 * @author: Ray
 * @date: 2023年08月28日 11:36
 */
public class ExceptionTest {
    public static void main(String[] args) throws RuntimeException, IOException {
        //小例子
//        try {
//            Integer a = 4/0;
//        } catch (Exception e) {
//            System.out.println("e.getMessage() = " + e.getMessage());
//            System.out.println("e.getCause() = " + e.getCause());
//            e.printStackTrace(); //详细
//            System.out.println("Exception thrown  :"+ e); //简略
//        }

//        try {
//            int[] a = new int[2];
//            System.out.println("a[2] = " + a[2]);
//        }catch (RuntimeException e){
//            System.out.println("catch到错误，并进行打印：");
//            e.printStackTrace();
//        }finally {
//            System.out.println("执行finally方法");
//        }
//        System.out.println("程序继续向下执行。。。");

//        int n = 3;
//        if(n < 4){
//            throw new RuntimeException("n can not less then four");
//        }

//try-with-resources 处理多个资源


    }
}
